### PR TITLE
WIP: add more support for distro package names

### PR DESCRIPTION
**Pull request by pabs3**
These will be useful for distros trying to link to Repology.

### CODE REVIEW

**Comment by pabs3** [comment]
The Codacy errors seem to be bogus, it doesn't seem to be able to parse Python typing syntax and doesn't know the .sql files are templates rather than SQL files.

**Comment by AMDmi3** [comment]
This is not acceptable due to multiple reasons:
- most packages no longer have `name`
- you can't look into `packages` table in query_metapackages due to performance reasons
- separate field for package name is a no-go from UX perspective

Also multiple tasks are touched by this PR at once:
- URLs based on original package names (#66)
-Search based on original package names (#111)

**Comment by pabs3** [comment]
On Wed, 2020-01-22 at 05:30 -0800, Dmitry Marakasov wrote:

> This is not acceptable due to multiple reasons:

Are there any other issues if I fix the ones you mentioned?

> most packages no longer have name

I see from #66 and #944 that this is because there are now name,
srcname and or binname fields depending on which distro it is.

> you can't look into packages table in query_metapackages due to
> performance reasons

I had planned to add an index to speed up those queries.

> separate field for package name is a no-go from UX perspective

How can package name searches happen without a separate field?

> Also multiple tasks are touched by this PR at once

I'll separate them into multiple PRs.

> * URLs based on original package names (#66)
> * Search based on original package names (#111)

Thanks for linking to the issues for these, I wasn't able to find them
in the issues list.

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by AMDmi3** [comment]
> Are there any other issues if I fix the ones you mentioned?

Well this would require more of rewriting from scratch than fixing specific issues, as different approach is needed for both tasks. But it'd be great if you implement them, just some discussion is needed.

Let's move to #66 for packagename-specific urls.

The following is related to search by package name.

> I had planned to add an index to speed up those queries.

It won't suffice. First, you can't really add new indexes on `packages` table as it leads to thrashing during the update and severe slowdown, and these indexes won't be effective anyway because there are a lot of repeated values for each field.

> How can package name searches happen without a separate field?

The first idea was to not do package name searches (in fact, filtering) in project listing and use separate generic search instead as mentioned in #111. However after some thought, there might be a solution. May discuss it in repology/repology-updater#995.

**Pull request closed without merging**
